# a digest suffix must not hide the unsafe "golang" image name
# Noncompliant@+1 {{The "golang" image runs with "root" as the default user. Make sure it is safe here.}}
FROM golang@sha256:06b5d30fabc1
ENTRYPOINT ["/app"]
