FROM scratch

## All sensitive numbers
# Noncompliant@+1 {{Make sure granting write access to others is safe here.}}
  RUN chmod 002
#     ^^^^^^^^^
# Noncompliant@+1
RUN chmod 003
# Noncompliant@+1
RUN chmod 006
# Noncompliant@+1
RUN chmod 007
# Noncompliant@+1
RUN chmod 2000
# Noncompliant@+1
RUN chmod 3000
# Noncompliant@+1
RUN chmod 4000
# Noncompliant@+1
RUN chmod 5000
# Noncompliant@+1
RUN chmod 6000
# Noncompliant@+1
RUN chmod 7000

## All sensitive AlphaNumerical
# Noncompliant@+1
RUN chmod o+w
# Noncompliant@+1
RUN chmod a+w
# Noncompliant@+1
RUN chmod +w
# Noncompliant@+1
RUN chmod o+wx
# Noncompliant@+1
RUN chmod a+wx
# Noncompliant@+1
RUN chmod +wx
# Noncompliant@+1
RUN chmod o+wX
# Noncompliant@+1
RUN chmod a+wX
# Noncompliant@+1
RUN chmod +wX
# Noncompliant@+1
RUN chmod o+rw
# Noncompliant@+1
RUN chmod a+rw
# Noncompliant@+1
RUN chmod +rw
# Noncompliant@+1
RUN chmod o+rwx
# Noncompliant@+1
RUN chmod a+rwx
# Noncompliant@+1
RUN chmod +rwx
# Noncompliant@+1
RUN chmod o+rwX
# Noncompliant@+1
RUN chmod a+rwX
# Noncompliant@+1
RUN chmod +rwX
# Noncompliant@+1
RUN chmod g+s
# Noncompliant@+1
RUN chmod g+st
# Noncompliant@+1
RUN chmod u+s
# Noncompliant@+1
RUN chmod u+st
# Noncompliant@+1
RUN chmod gu+s
# Noncompliant@+1
RUN chmod +s
# Noncompliant@+1
RUN chmod gu+st
# Noncompliant@+1
RUN chmod +st

## All compliant numbers
RUN chmod 000
RUN chmod 001
RUN chmod 004
RUN chmod 005
RUN chmod 0000
RUN chmod 1000

## All compliant AlphaNumerical
RUN chmod o+x
RUN chmod a+x
RUN chmod +x
RUN chmod o+r
RUN chmod a+r
RUN chmod +r
RUN chmod o+X
RUN chmod a+X
RUN chmod +X
RUN chmod g+t
RUN chmod u+t
RUN chmod +t


## Other cases
ARG sensitive_right=002
ARG compliant_right=000
ARG sensitive_digit=2
ARG compliant_digit=0

# Sensitive
# Noncompliant@+1
RUN chmod 0002
# Noncompliant@+1
RUN chmod 02
# Noncompliant@+1
RUN chmod 2
# Noncompliant@+1
RUN chmod 2002
# Noncompliant@+1
RUN chmod -R 002
# Noncompliant@+1
RUN chmod --recursive 002
# Noncompliant@+1
RUN chmod --recursive -f --changes 002
# Noncompliant@+1
RUN chmod 002 resource
# Noncompliant@+1
RUN chmod 002 src dest
# Noncompliant@+1
RUN chmod 002 \
  resource && \
  other_command
# Noncompliant@+1
RUN other_command && chmod 002 resource && other_command
# Noncompliant@+1
RUN chmod 00$sensitive_digit
# Noncompliant@+1
RUN chmod 00${sensitive_digit}
# Noncompliant@+1
RUN chmod $sensitive_right
# Noncompliant@+1
RUN ["chmod", "002"]
# Noncompliant@+1
RUN ["chmod", "-R", "002"]
# Noncompliant@+1
RUN ["chmod", "o+w"]
# Noncompliant@+1
RUN chmod o=w
# Noncompliant@+1
RUN chmod o+rw
# Noncompliant@+1
RUN chmod o+wr
# Noncompliant@+1
RUN chmod u+w,o+w
# Noncompliant@+1
RUN chmod u+r,o+w
# Noncompliant@+1
RUN chmod o+w,u+r
# Noncompliant@+1
  RUN chmod u-w,o+w
#     ^^^^^^^^^^^^^
# Noncompliant@+1
  RUN chmod u+wr resource && chmod o+w resource
#                            ^^^^^^^^^
# Noncompliant@+1
RUN chmod o+w resource && chmod u+wr resource
# Noncompliant@+1
RUN chmod chmod o+w resource
# Noncompliant@+1
RUN chmod g=u,o+w resource
# Noncompliant@+2
RUN <<-SCRIPT
  chmod +st
# ^^^^^^^^^
SCRIPT

# Compliant
RUN chmod 0000
RUN chmod -R 000
RUN chmod --recursive 000
RUN chmod --recursive -f --changes 000
RUN chmod 000 resource
RUN chmod 000 src dest
RUN chmod 000 \
  resource && \
  other_command
RUN other_command && chmod 000 resource && other_command
RUN chmod 00$compliant_digit
RUN chmod 00${compliant_digit}
RUN chmod $compliant_right
RUN ["chmod", "0", "0", "2"]
RUN ["chmod", "random", "002"]
RUN ["chmod", "u+w"]
RUN chmod o+rx
RUN chmod o+xr
RUN chmod o+rX
RUN chmod u+w
RUN chmod o-w
RUN chmod u+wr
RUN chmod u=wr
RUN chmod u+w,o-w
RUN chmod u+w resource && chmod u+wr resource
RUN <<-SCRIPT
  chmod u+w
SCRIPT

## Specific case which can cause parsing error
RUN chmod
RUN chmod -R
RUN chmod u+wr,
RUN chmod u=g
RUN ["chmod"]
RUN ["chmod", "-R"]
