env:

  ARTIFACTORY_URL: VAULT[development/kv/data/repox data.url]
  ARTIFACTORY_PRIVATE_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader
  ARTIFACTORY_PRIVATE_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  ARTIFACTORY_DEPLOY_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer
  ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]
  #Possible values for ARTIFACTORY_DEPLOY_REPO: sonarsource-private-qa, sonarsource-public-qa
  ARTIFACTORY_DEPLOY_REPO: sonarsource-public-qa
  ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  # Use bash (instead of sh on linux or cmd.exe on windows)
  CIRRUS_SHELL: bash
  # Allows to run builds for the 50 last commits in a branch:
  CIRRUS_CLONE_DEPTH: 1

  GO_VERSION: 1.21.1
  PROTOC_VERSION: 25.0

maven_cache: &MAVEN_CACHE
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
    fingerprint_script: cat **/pom.xml

build_secrets: &BUILD_SECRETS
  SIGN_KEY: VAULT[development/kv/data/sign data.key]
  PGP_PASSPHRASE: VAULT[development/kv/data/sign data.passphrase]
  # analysis on SonarCloud
  SONAR_HOST_URL: https://sonarcloud.io
  SONAR_TOKEN: VAULT[development/kv/data/sonarcloud data.token]

ws_scan_secrets: &WS_SCAN_SECRETS
  WS_APIKEY: VAULT[development/kv/data/mend data.apikey]

promote_secrets: &PROMOTE_SECRETS
  ARTIFACTORY_PROMOTE_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promoter access_token]
  GITHUB_TOKEN: VAULT[development/github/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promotion token]
  # burgr notification
  BURGR_URL: VAULT[development/kv/data/burgr data.url]
  BURGR_USERNAME: VAULT[development/kv/data/burgr data.cirrus_username]
  BURGR_PASSWORD: VAULT[development/kv/data/burgr data.cirrus_password]

# ----------------------------------------------
# -------------CONTAINER DEFINITIONS------------
# ----------------------------------------------

linux_image_template: &LINUX_IMAGE
  image: ${CIRRUS_AWS_ACCOUNT}.dkr.ecr.eu-central-1.amazonaws.com/base:j17-latest
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  region: eu-central-1
  namespace: default
  use_in_memory_disk: true

linux_image_with_gcc_template: &LINUX_IMAGE_WITH_GCC
  dockerfile: .cirrus/Dockerfile
  docker_arguments:
    CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
    GO_VERSION: ${GO_VERSION}
    PROTOC_VERSION: ${PROTOC_VERSION}
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  builder_role: cirrus-builder
  builder_image: docker-builder-v*
  builder_instance_type: t3.small
  builder_subnet_id: ${CIRRUS_AWS_SUBNET}
  region: eu-central-1
  namespace: default
  use_in_memory_disk: true

linux_1_cpu_1G_template: &LINUX_1_CPU_1G
  eks_container:
    <<: *LINUX_IMAGE
    cpu: 1
    memory: 1G

linux_4_cpu_8G_java_17_template: &LINUX_4_CPU_8G_JAVA_17
  eks_container:
    <<: *LINUX_IMAGE
    image: ${CIRRUS_AWS_ACCOUNT}.dkr.ecr.eu-central-1.amazonaws.com/base:j17-latest
    cpu: 4
    memory: 8G

win_vm_definition: &WINDOWS_VM_DEFINITION
  ec2_instance:
    experimental: true # see https://github.com/cirruslabs/cirrus-ci-docs/issues/1051
    image: base-windows-jdk17-v*
    platform: windows
    region: eu-central-1
    type: t3.xlarge
    subnet_id: ${CIRRUS_AWS_SUBNET}
    use_ssd: true

# ----------------------------------------------
# ------------------FILTERS---------------------
# ----------------------------------------------

only_sonarsource_qa: &ONLY_IF_SONARSOURCE_QA
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_TAG == "" &&
    ($CIRRUS_PR != "" || $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "dogfood-on-.*")

only_main_branches: &ONLY_MAIN_BRANCHES
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_TAG == "" &&
    ($CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_BRANCH =~ "branch-.*")

qa_task_filter_template: &QA_TASK_FILTER
  depends_on:
    - build
  <<: *ONLY_IF_SONARSOURCE_QA

# ----------------------------------------------
# -------------------TASKS----------------------
# ----------------------------------------------

build_task:
  eks_container:
    <<: *LINUX_IMAGE_WITH_GCC
    cpu: 3.5
    memory: 7G
  <<: *MAVEN_CACHE
  env:
    <<: *BUILD_SECRETS
    #allow deployment of pull request artifacts to repox
    DEPLOY_PULL_REQUEST: true
    GO_CROSS_COMPILE: '1'
  build_script:
    - source cirrus-env BUILD
    - go version
    - regular_mvn_build_deploy_analyze
  cleanup_before_cache_script: cleanup_maven_repository

qa_os_win_task:
  <<: *QA_TASK_FILTER
  <<: *WINDOWS_VM_DEFINITION
  maven_cache:
    #windows cache is buggy if using ${CIRRUS_WORKING_DIR}
    folder: ~/.m2/repository
  _lib:
    # For windows, refresh the path env variable, particularly useful after an installation with choco (RefreshEnv.cmd cannot be used in this context)
    - &refreshpath eval $(powershell -NonInteractive -Command 'write("export PATH=`"" + ([Environment]::GetEnvironmentVariable("PATH","Machine") + ";" + [Environment]::GetEnvironmentVariable("PATH","User")).replace("\","/").replace("C:","/c").replace(";",":") + ":`$PATH`"")')
  build_script:
    - choco install golang --version ${GO_VERSION}
    - choco install protoc --version ${PROTOC_VERSION}.0
    - *refreshpath
    - source cirrus-env CI
    - mvn.cmd clean verify

sca_scan_task:
  depends_on:
    - build
  <<: *MAVEN_CACHE
  <<: *ONLY_MAIN_BRANCHES
  eks_container:
    <<: *LINUX_IMAGE_WITH_GCC
  env:
    <<: *WS_SCAN_SECRETS
  whitesource_script:
    - source cirrus-env QA
    - source set_maven_build_version $BUILD_NUMBER
    - mvn clean install -DskipTests -P-ci,local
    - source ws_scan.sh -d "${PWD},${PWD}/sonar-helm-for-iac"
  allow_failures: "true"
  always:
    ws_artifacts:
      path: "whitesource/**/*"

qa_plugin_task:
  <<: *QA_TASK_FILTER
  <<: *LINUX_4_CPU_8G_JAVA_17
  <<: *MAVEN_CACHE
  env:
    matrix:
      - SQ_VERSION: LATEST_RELEASE
      - SQ_VERSION: DEV
  submodules_script:
    - git submodule update --init
  plugin_script:
    - source cirrus-env QA
    - source set_maven_build_version $BUILD_NUMBER
    - cd its/plugin
    - mvn verify -Drevision=${PROJECT_VERSION} -Dsonar.runtimeVersion=${SQ_VERSION} -B -e -V
  cleanup_before_cache_script: cleanup_maven_repository

qa_ruling_task:
  <<: *QA_TASK_FILTER
  <<: *LINUX_4_CPU_8G_JAVA_17
  <<: *MAVEN_CACHE
  submodules_script:
    - git submodule update --init
  ruling_script:
    - source cirrus-env QA
    - source set_maven_build_version $BUILD_NUMBER
    - cd its/ruling
    - mvn verify -Dsonar.runtimeVersion=LATEST_RELEASE -B -e -V
  cleanup_before_cache_script: cleanup_maven_repository

promote_task:
  depends_on:
    - build
    - qa_ruling
    - qa_plugin
  <<: *ONLY_IF_SONARSOURCE_QA
  <<: *LINUX_1_CPU_1G
  <<: *MAVEN_CACHE
  env:
    <<: *PROMOTE_SECRETS
    #artifacts that will have downloadable links in burgr
    ARTIFACTS: com.sonarsource.iac:sonar-iac-plugin:jar
  script: cirrus_promote_maven
  cleanup_before_cache_script: cleanup_maven_repository
