env:
  CIRRUS_SHELL: bash

build_task:
  skip: $CIRRUS_BRANCH == "public_master"
  eks_container:
    dockerfile: build-logic/iac/Dockerfile
    cpu: 2
    memory: 10G
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
      GO_VERSION: "1.23.4"
    builder_role: cirrus-builder
    builder_image: "docker-builder-v*"
    builder_subnet_id: ${CIRRUS_AWS_SUBNET}
    builder_instance_type: t3.small
    cluster_name: ${CIRRUS_CLUSTER_NAME}
    region: eu-central-1
    namespace: default
    use_in_memory_disk: true
  env:
    SONAR_HOST_URL: https://sonarcloud.io
    SONAR_TOKEN: ENCRYPTED[!7a28d43095ea7e33c5e581fa3a6592ed0ac609d512213590cf41ce096e0849f360eb2f0881d7728f30cb148bed866ca5!]
    GRADLE_USER_HOME: ${CIRRUS_WORKING_DIR}/.gradle
    GRADLE_VERSION: "8.12"
  gradle_cache:
    folder: ${GRADLE_USER_HOME}/caches
    fingerprint_script: find -type f \( -name "*.gradle*" -or -name "gradle*.properties" \) | sort | xargs cat
    populate_script: mkdir -p ${GRADLE_USER_HOME}/caches
  script:
    - git submodule update --init --depth 1 -- build-logic/common
    - ./build.sh
  cleanup_gradle_script: |
    rm -rf "${GRADLE_USER_HOME}/caches/$GRADLE_VERSION/"
    rm -rf "${GRADLE_USER_HOME}"/daemon/
    rm -rf "${GRADLE_USER_HOME}"/caches/transforms-*
    rm -rf "${GRADLE_USER_HOME}"/caches/journal-*
    /usr/bin/find "${GRADLE_USER_HOME}"/caches/ -name "*.lock" -type f -delete
