env:
  CIRRUS_VAULT_URL: https://vault.sonar.build:8200
  CIRRUS_VAULT_AUTH_PATH: jwt-cirrusci
  CIRRUS_VAULT_ROLE: cirrusci-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}

  CIRRUS_SHELL: bash
  DEPLOY_PULL_REQUEST: false
  CRON_NIGHTLY_JOB_NAME: "nightly"

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_TAG == "" && ($CIRRUS_PR != "" || $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "dogfood-on-.*")


build_container_definition: &BUILD_CONTAINER_DEFINITION
  eks_container:
    dockerfile: build-logic/iac/Dockerfile
    cpu: 2
    memory: 10G
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
      GO_VERSION: "1.23.4"
    builder_role: cirrus-builder
    builder_image: "docker-builder-v*"
    builder_subnet_id: ${CIRRUS_AWS_SUBNET}
    builder_instance_type: t3.small
    cluster_name: ${CIRRUS_CLUSTER_NAME}
    region: eu-central-1
    namespace: default
    use_in_memory_disk: true

base_analysis_template: &BASE_ANALYSIS
  <<: *BUILD_CONTAINER_DEFINITION
  <<: *ONLY_SONARSOURCE_QA
  env:
    GRADLE_USER_HOME: ${CIRRUS_WORKING_DIR}/.gradle
    GRADLE_VERSION: "8.12"
  gradle_cache:
    folder: ${GRADLE_USER_HOME}/caches
    fingerprint_script: find -type f \( -name "*.gradle*" -or -name "gradle*.properties" \) | sort | xargs cat
    populate_script: mkdir -p ${GRADLE_USER_HOME}/caches
  script:
    - git submodule update --init --depth 1 -- build-logic/common
    - ./build.sh
  cleanup_gradle_script: |
    rm -rf "${GRADLE_USER_HOME}/caches/$GRADLE_VERSION/"
    rm -rf "${GRADLE_USER_HOME}"/daemon/
    rm -rf "${GRADLE_USER_HOME}"/caches/transforms-*
    rm -rf "${GRADLE_USER_HOME}"/caches/journal-*
    /usr/bin/find "${GRADLE_USER_HOME}"/caches/ -name "*.lock" -type f -delete

# primary analysis
build_task:
  <<: *BASE_ANALYSIS
  alias: analysis_next
  name: "Build and analysis on SonarQube NEXT"
  env:
    SONAR_TOKEN: VAULT[development/kv/data/next data.token]
    SONAR_HOST_URL: https://next.sonarqube.com/sonarqube
    SONAR_PROJECT_KEY: SonarSource_sonar-iac

analysis_sqc_eu_shadow_task:
  <<: *BASE_ANALYSIS
  alias: analysis_sqc_eu_shadow
  name: "Analysis on Sonarcloud.io"
  only_if: ($CIRRUS_CRON == $CRON_NIGHTLY_JOB_NAME && $CIRRUS_BRANCH == "master") || $CIRRUS_PR_LABELS =~ ".*shadow_scan.*"
  env:
    SONAR_TOKEN: VAULT[development/kv/data/sonarcloud data.token]
    SONAR_HOST_URL: https://sonarcloud.io
    SONAR_PROJECT_KEY: org.sonarsource.iac:iac

analysis_sqc_us_shadow_task:
  <<: *BASE_ANALYSIS
  alias: analysis_sqc_us_shadow
  name: "Analysis on SonarQube.us"
  only_if: ($CIRRUS_CRON == $CRON_NIGHTLY_JOB_NAME && $CIRRUS_BRANCH == "master") || $CIRRUS_PR_LABELS =~ ".*shadow_scan.*"
  env:
    SONAR_TOKEN: VAULT[development/kv/data/sonarqube-us data.token]
    SONAR_HOST_URL: https://sonarqube.us
    SONAR_PROJECT_KEY: SonarSource_sonar-iac
