apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    helmVersion: {{ .Capabilities.HelmVersion.Version }}
    kubeVersion: {{ .Capabilities.KubeVersion.Version }}
  labels:
    appName: {{ .Chart.Name }}
    name: {{ .Template.Name }}
    revision: {{ .Release.Revision }}

{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
# A comment for newer K8s versions
{{- end }}
{{- end }}
