apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: test-tpl
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      securityContext:
        allowPrivilegeEscalation: {{ tpl .Values.escalation . }}
