ARG GLOBAL_PORT_1=22
ARG GLOBAL_PORT_2=22

FROM foo

ARG GLOBAL_PORT_1

# Noncompliant@+1 {{Make sure that exposing administration services is safe here.}}
EXPOSE 22
#      ^^

# Noncompliant@+1 {{Make sure that exposing administration services is safe here.}}
EXPOSE 22/tcp
#      ^^^^^^

# Noncompliant@+1
EXPOSE 23
# Noncompliant@+1
EXPOSE 3389
# Noncompliant@+1
EXPOSE 5800
# Noncompliant@+1
EXPOSE 5900

EXPOSE 80
EXPOSE 222
EXPOSE 33891

EXPOSE 22/udp

# Noncompliant@+1
EXPOSE 40 80 22 20
#            ^^

# Noncompliant@+1
EXPOSE 40 80 22/tcp 20
#            ^^^^^^

# Noncompliant@+1
EXPOSE 20-25

# Noncompliant@+1
EXPOSE 22-23/tcp

EXPOSE 22-23/udp

ARG SENSITIVE_EXPOSE=22/tcp
ARG SENSITIVE_PORT=22
ARG SENSITIVE_PROTOCOL=tcp
ARG COMPLIANT_PROTOCOL=udp

# Noncompliant@+1
EXPOSE $SENSITIVE_EXPOSE

# Noncompliant@+1
EXPOSE $SENSITIVE_PORT

# Noncompliant@+1
EXPOSE 20 $SENSITIVE_PORT

EXPOSE $SENSITIVE_PORT/UDP

# Noncompliant@+1
EXPOSE 22/$SENSITIVE_PROTOCOL

EXPOSE 22/$COMPLIANT_PROTOCOL

# Noncompliant@+1
EXPOSE $GLOBAL_PORT_1

# GLOBAL_PORT_2 is not accesible in this scope
EXPOSE $GLOBAL_PORT_2

EXPOSE FOO

# TODO SONARIAC-596 Include default value when resolving an encapsulated variable
EXPOSE ${UNKNOWN_PORT:-22}

# TODO SONARIAC-597 Include value insert when resolving an encapsulated variable
ARG SENSITIVE_PORT=22
EXPOSE ${SENSITIVE_PORT:+80}
