apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - image: k8s.gcr.io/test-webserver
      name: test-container
      securityContext:
{{ if .Values.capabilities }}
        capabilities:
          add:
{{- range .Values.capabilities }}
            - {{ . | quote }}
{{- end }}
{{- end }}
