apiVersion: v1
kind: Pod
metadata:
  name: example
  description: Some text without double quotes
  description2: multiline
    unquoted
    description
spec:
  containers:
    - image: k8s.gcr.io/test-webserver
      name: test-container
      securityContext:
        capabilities:
          add:
{{- range .Values.capabilities }}
            - {{ . | quote }}
{{- end }}
