{{- /*
  Line 1
  Line 2
*/ -}}
apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    {{-
      if .Values.annotations
    }} {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value | quote }} {{- end }}{{- end }}
    cfg: |-
      {{- if or
        (eq "abc" .Values.foo)
        (eq "def" .Values.bar)
      }}
      if
      {{- else }}
      else
      {{- end }}
spec:
  containers:
    - image: k8s.gcr.io/test-webserver
      name: test-container
