apiVersion: v1
kind: Pod
metadata:
  {{ toYaml .Values.metadataPod }}
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      securityContext:
        allowPrivilegeEscalation: true
