FROM foo

# Noncompliant@+1 {{Make sure that exposing administration services is safe here.}}
EXPOSE 22
#      ^^

# Noncompliant@+1 {{Make sure that exposing administration services is safe here.}}
EXPOSE 22/tcp
#      ^^^^^^

# Noncompliant@+1
EXPOSE 23
# Noncompliant@+1
EXPOSE 3389
# Noncompliant@+1
EXPOSE 5800
# Noncompliant@+1
EXPOSE 5900

EXPOSE 80
EXPOSE 222
EXPOSE 33891

EXPOSE 22/udp

# Noncompliant@+1
EXPOSE 40 80 22 20
#            ^^

# Noncompliant@+1
EXPOSE 40 80 22/tcp 20
#            ^^^^^^

# Noncompliant@+1
EXPOSE 20-25

# Noncompliant@+1
EXPOSE 22-23/tcp

EXPOSE 22-23/udp

ARG SENSITIVE_EXPOSE=22/tcp
ARG SENSITIVE_PORT=22
ARG SENSITIVE_PROTOCOL=tcp
ARG COMPLIANT_PROTOCOL=udp

# FN
EXPOSE $SENSITIVE_EXPOSE

# FN
EXPOSE $SENSITIVE_PORT

# FN
EXPOSE 20 $SENSITIVE_PORT

EXPOSE $SENSITIVE_PORT/UDP

# FN
EXPOSE 22/$SENSITIVE_PROTOCOL

EXPOSE 22/$COMPLIANT_PROTOCOL


EXPOSE FOO
