FROM ubuntu:22.04

# Noncompliant@+1 {{Copying recursively might inadvertently add sensitive data to the container. Make sure it is safe here.}}
COPY . /example
#    ^

# Noncompliant@+1
COPY ./ /example

# Noncompliant@+1
COPY ./. /example

# Noncompliant@+1
COPY .//. /example

# Noncompliant@+1
COPY ./test/.. /example

# Noncompliant@+1
COPY ./test/./.. /example

# Noncompliant@+1
COPY / /example

# Noncompliant@+1
COPY /. /example

# Noncompliant@+1
COPY /./test/.. /example

# Noncompliant@+1
COPY /.. /example

# Noncompliant@+1
COPY /../test/.. /example

# Noncompliant@+1
COPY /./ /example

# Noncompliant@+1
COPY /.// /example

# Noncompliant@+1
COPY c:/ /example
#    ^^^

# Noncompliant@+1
COPY c:/test/.. /example

# Noncompliant@+1
COPY c:/. /example

# Noncompliant@+1
COPY c:/.. /example

# Noncompliant@+1
COPY / /source2 /example
#    ^

# Noncompliant@+1
COPY /source1 / /example
#             ^

# Noncompliant@+1
COPY "/" /example

# Noncompliant@+1 {{Copying using a glob pattern might inadvertently add sensitive data to the container. Make sure it is safe here.}}
COPY /a* /example

# Noncompliant@+1
COPY a* /example

# Noncompliant@+1
COPY ./a*/ /example

# Noncompliant@+1
COPY /test/../a* /example

# Noncompliant@+1
COPY c:/a* /example

# Noncompliant@+1
COPY c:/../a* /example

# Noncompliant@+1
COPY /../a* /example

# Noncompliant@+1
COPY ./a*/ /example

# Noncompliant@+1
COPY /test/../a* /example

# Noncompliant@+1
COPY ./a*/.. /example

COPY ./example /example
COPY "./example" /example
# FN
COPY ./test/../test /example
COPY ./../test /example
COPY /test
COPY /test/../test
COPY ..
COPY ../test
COPY c:/temp /example
COPY c:/./temp /example
COPY c:/../temp /example
COPY /source1 /source2 /example
COPY ./c:/ /example
COPY ./test/a* /example
COPY ./*.py /example
COPY ./*a /example
COPY *a /example
COPY ./a*/../test /example
COPY ./a*/test /example
COPY ./a*/*.py /example
COPY /a*/*.py /example
COPY ./test/a* /example
COPY /test/a* /example
COPY test/a* /example

# Specific COPY use case
COPY --from . /example
COPY --from=bob "/" /example

# FN, we don't handle yet element **
COPY ./a/** /example

COPY ${JAR_FILE} application.jar
COPY "${JAR_FILE}" application.jar
COPY "${JAR_FILE:-file.jar}" application.jar
COPY "${JAR_FILE:+file.jar}" application.jar
COPY 'file.jar' application.jar

COPY <<EOF /workbench/trace.sh
#!/usr/bin/env bash
echo "********"
EOF
