FROM ubuntu:22.04

# Noncompliant@+1 {{Adding files recursively might inadvertently add sensitive data to the container. Make sure it is safe here.}}
ADD . /example
#   ^

# Noncompliant@+1
ADD ./ /example

# Noncompliant@+1
ADD ./. /example

# Noncompliant@+1
ADD .//. /example

# Noncompliant@+1
ADD ./test/.. /example

# Noncompliant@+1
ADD ./test/./.. /example

# Noncompliant@+1
ADD / /example

# Noncompliant@+1
ADD /. /example

# Noncompliant@+1
ADD /./test/.. /example

# Noncompliant@+1
ADD /.. /example

# Noncompliant@+1
ADD /../test/.. /example

# Noncompliant@+1
ADD /./ /example

# Noncompliant@+1
ADD /.// /example

# Noncompliant@+1
ADD c:/ /example
#   ^^^

# Noncompliant@+1
ADD c:/test/.. /example

# Noncompliant@+1
ADD c:/. /example

# Noncompliant@+1
ADD c:/.. /example

# Noncompliant@+1
ADD / /source2 /example
#   ^

# Noncompliant@+1
ADD /source1 / /example
#            ^

# Noncompliant@+1
ADD "/" /example

# Noncompliant@+1 {{Adding files using a glob pattern might inadvertently add sensitive data to the container. Make sure it is safe here.}}
ADD /a* /example

# Noncompliant@+1
ADD a* /example

# Noncompliant@+1
ADD ./a*/ /example

# Noncompliant@+1
ADD /test/../a* /example

# Noncompliant@+1
ADD c:/a* /example

# Noncompliant@+1
ADD c:/../a* /example

# Noncompliant@+1
ADD /../a* /example

# Noncompliant@+1
ADD http:/.. /example

# Noncompliant@+1
ADD ./a*/.. /example

ADD ./example /example
ADD "./example" /example
ADD ./test/../test /example
ADD ./../test /example
ADD /test
ADD /test/../test
ADD ..
ADD ../test
ADD c:/temp /example
ADD c:/./temp /example
ADD c:/../temp /example
ADD /source1 /source2 /example
ADD ./c:/ /example
ADD ./test/a* /example
ADD ./*.py /example
ADD ./*a /example
ADD *a /example
ADD ./a*/../test /example
ADD ./a*/test /example
ADD ./a*/*.py /example
ADD /a*/*.py /example

# specific ADD use case
ADD http://.. /example
ADD https://.. /example
ADD "http://.." /example

# Unlike COPY, the --from option does not prevent raising issue
# Noncompliant@+1
ADD --from . /example

# FN, we don't handle yet element **
ADD ./a/** /example


ADD ${JAR_FILE} application.jar
ADD "${JAR_FILE}" application.jar
ADD "${JAR_FILE:-file.jar}" application.jar
ADD "${JAR_FILE:+file.jar}" application.jar
ADD 'file.jar' application.jar
