capabilities:
  - SYS_ADMIN
  - NET_ADMIN
foo: foo-value
bar: bar-value
annotations:
  first: foobar
  second: barfoo
# TODO The TODOs in values.yaml should be detected if it not contains Helm expressions
livenessProbe: true
initialDelaySeconds: 5
multiline: |
  .
  .
  .
  .

container:
  name: some-container-name
  privileged: true
