AWSTemplateFormatVersion: 2010-09-09
testAnchor: &testAnchor
  Key: "anycompany:cost-center" # Noncompliant - Currently we do raise two issue in this location. We should avoid this SONARIAC-78
  Value: "Accounting"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "mybucketname"
      Tags:
        - Key: "anycompany:cost-center" # Noncompliant
          Value: "Accounting"
        - Key: "anycompany:EnvironmentType" # Noncompliant
          Value: "PROD"
        - Key: "Anycompany:CostCenter"
          Value: "Accounting"
        - Key: "Anycompany:EnvironmentType"
          Value: "PROD"
        - *testAnchor
        - *testAnchor
