AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Notebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: "ml.t2.medium"
      RoleArn:
        Fn::GetAtt:
          - TestRole
          - Arn

  NotebookEncrypted:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: "ml.t2.medium"
      RoleArn:
        Fn::GetAtt:
          - TestRole
          - Arn
      KmsKeyId:
        Fn::GetAtt:
          - TestKey
          - KeyId

  OtherResource1:
    Type: AWS::EC2::Volume
    Properties:
      Encrypted: true

  OtherResource2:
    Type: unknown
