AWSTemplateFormatVersion: '2010-09-09'
Resources:
  UnencryptedQueue:
    Type: AWS::SQS::Queue
    Properties:
     "DisplayName": "unencrypted_queue"

  EncryptedQueue:
    Type: AWS::SQS::Queue
    Properties:
      DisplayName: "encrypted_queue"
      KmsMasterKeyId:
        Fn::GetAtt:
          - TestKey
          - KeyId

  OtherResource1:
    Type: AWS::EC2::Volume
    Properties:
      Encrypted: true

  OtherResource2:
    Type: unknown
