apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: {{ required "The value is present, it will be replaced succesfully and another issue will be raised on the file" .Values.name }}
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      securityContext:
        allowPrivilegeEscalation: {{ .Values.escalation }}
