FROM scratch

# Noncompliant@+1 {{Line is too long. Split it into multiple lines using backslash continuations.}}
RUN this short instruction is now sufficient to trigger

RUN butThereIsStill theLimit OnThe NumberOfWords

# Noncompliant@+1
RUN very long instruction are still raised as before aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
