apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: default-mem-example
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
        ephemeral-storage: "10Mi"
