apiVersion: v1
kind: Pod
metadata:
  name: nginx-ns-compliant
  namespace: default-mem-example
spec:
  containers:
    - name: nginx-ns-compliant
      image: nginx
    # Without cross-file LimitRange detection S6869 and S6864 would be raised
