apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: test
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      securityContext:
        allowPrivilegeEscalation: {{ include "get-escalation-value" . }}
