name: bump-versions
on:
  workflow_dispatch:
    inputs:
      version:
        description: The new version
        required: true
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write # write for peter-evans/create-pull-request, read for actions/checkout
      pull-requests: write # write for peter-evans/create-pull-request
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - run: |
          sed -i 's/version=.*/version=${{ github.event.inputs.version }}/' gradle.properties
      - uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5
        with:
          author: ${{ github.actor }} <${{ github.actor }}>
          commit-message: Prepare next development iteration
          title: Prepare next development iteration
          branch: bot/bump-project-version
          branch-suffix: timestamp
